<?php
ob_start(); 
session_start();

$errors = array();
$_SESSION['Inactive'] = 0;
$_SESSION['LAST_ACTIVITY'] = time();



//THIS DEALS WITH REGISTERATION LOGIC 
if(isset($_POST['register'])){ 
    $connection = new mysqli('localhost','root','', 'srs');
    

    $idRegister = $connection->real_escape_string($_POST['idReg']);
    $email = $connection->real_escape_string($_POST['emailPHP']);
    $password1 = $connection->real_escape_string($_POST['password1PHP']);
    $password2 = $connection->real_escape_string($_POST['password2PHP']);

    //check if db has already an account with that email
    $user_check_query ="select * from loginform where Email ='".$email."' limit 1";

    $results = mysqli_query($connection, $user_check_query);
    $user = mysqli_fetch_assoc($results);

    if($user) {

        if($user['Email'] == $email) {
            array_push($errors,"This email is already registered");
            exit("Failure");
        }
       
      
    }

    //if db doesnt have account with that email check the id generated by the javascript if it exists anywhere since it must be unique
    if(count($errors)==0) {

            //check if db has already an account with that id
            $user_check_query ="select * from loginform where Username ='".$idRegister."' limit 1";

            $results = mysqli_query($connection, $user_check_query);
            $user = mysqli_fetch_assoc($results);

            if($user) {
                
                //if by somehow chance the id exists then create another random id and assign it to the user 
                if($user['Username'] == $idRegister) {
                    $randomNumber1 = rand(210,221);
                    $randomNumber2 = rand(0,9);
                    $randomNumber3 = rand(100,999);
                    $randomid = $randomNumber1*100000 + $randomNumber2*1000 + $randomNumber3;
                    $idRegister = $randomid;
                    $_POST['idReg'] = $idRegister;
                }
                
            
            }

        $passwordReg = $password1;
        $query = "INSERT INTO loginform (Email, Username, Password) VALUES ('$email', '$idRegister', '$passwordReg')";

        mysqli_query($connection, $query);
        exit("Success");
    }
}



//THIS DEALS WITH LOG IN LOGIC
//if already logged in
if(isset($_SESSION['loggedIN'])) {
    echo "Im inside here";
    header('Location: Success.php');
    exit();
}


    //connect php and mysqllite
    if(isset($_POST['login'])){ //everything is fine ready to login
        $connection = new mysqli('localhost','root','', 'srs');
    


        $id = $connection->real_escape_string($_POST['idPHP']);
        $password = $connection->real_escape_string($_POST['passwordPHP']);

        $sql="select * from loginform where Username ='".$id."'AND Password='".$password."'
        limit 1";

        $result = mysqli_query($connection, $sql);
        
        if(mysqli_num_rows($result)!=0){
        $_SESSION['loggedIN'] = 1;
        $_SESSION['id'] = $id;
            exit("Success");
        }

        else{
        
            exit("Failure");
        }
        

    }
?>